# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python\MissiaLProject\Sketches\gui\azk.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 200)
        MainWindow.setMinimumSize(QtCore.QSize(350, 200))
        MainWindow.setMaximumSize(QtCore.QSize(356, 595))
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle("Выкачивание сборок")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayoutAzk = QtWidgets.QVBoxLayout()
        self.verticalLayoutAzk.setContentsMargins(0, 0, -1, -1)
        self.verticalLayoutAzk.setSpacing(6)
        self.verticalLayoutAzk.setObjectName("verticalLayoutAzk")

        self.azkButton = QtWidgets.QPushButton(self.centralwidget)
        self.azkButton.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.azkButton.setFont(font)
        self.azkButton.setToolTip("Выкачать сборку АЦК-ФИНАНСЫ")
        self.azkButton.setStatusTip("")
        self.azkButton.setWhatsThis("")
        self.azkButton.setAccessibleName("")
        self.azkButton.setAccessibleDescription("")
        self.azkButton.setText("АЦК - ФИНАНСЫ")
        self.azkButton.setShortcut("1")
        self.azkButton.setFlat(False)
        self.azkButton.setObjectName("azkButton")
        #self.azkButton.clicked.connect()

        self.verticalLayoutAzk.addWidget(self.azkButton)
        self.verticalLayout_4.addLayout(self.verticalLayoutAzk)
        self.verticalLayoutGz = QtWidgets.QVBoxLayout()
        self.verticalLayoutGz.setSpacing(6)
        self.verticalLayoutGz.setObjectName("verticalLayoutGz")
        self.gzButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.gzButton.setFont(font)
        self.gzButton.setToolTip("Выкачать сборку АЦК-ГОСЗАКАЗ")
        self.gzButton.setStatusTip("")
        self.gzButton.setWhatsThis("")
        self.gzButton.setAccessibleName("")
        self.gzButton.setAccessibleDescription("")
        self.gzButton.setText("АЦК - ГОСЗАКАЗ")
        self.gzButton.setShortcut("")
        self.gzButton.setObjectName("gzButton")
        self.verticalLayoutGz.addWidget(self.gzButton)
        self.verticalLayout_4.addLayout(self.verticalLayoutGz)
        self.verticalLayoutBk = QtWidgets.QVBoxLayout()
        self.verticalLayoutBk.setSpacing(6)
        self.verticalLayoutBk.setObjectName("verticalLayoutBk")
        self.bkButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.bkButton.setFont(font)
        self.bkButton.setToolTip("Выкачивание сборки АЦК - БЮДЖЕТНЫЙ УЧЕТ")
        self.bkButton.setStatusTip("")
        self.bkButton.setWhatsThis("")
        self.bkButton.setAccessibleName("")
        self.bkButton.setAccessibleDescription("")
        self.bkButton.setText("АЦК - БЮДЖЕТНЫЙ УЧЕТ")
        self.bkButton.setObjectName("bkButton")
        self.verticalLayoutBk.addWidget(self.bkButton)
        self.verticalLayout_4.addLayout(self.verticalLayoutBk)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setToolTip("")
        self.menu.setStatusTip("")
        self.menu.setWhatsThis("")
        self.menu.setAccessibleName("")
        self.menu.setAccessibleDescription("")
        self.menu.setTitle("Меню")
        self.menu.setObjectName("menu")
        self.about = QtWidgets.QMenu(self.menubar)
        self.about.setToolTip("")
        self.about.setStatusTip("")
        self.about.setWhatsThis("")
        self.about.setAccessibleName("")
        self.about.setAccessibleDescription("")
        self.about.setTitle("О программе")
        self.about.setObjectName("about")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setCheckable(True)
        self.exit.setText("Выход")
        self.exit.setToolTip("Выход из программы")
        self.exit.setShortcut("Ctrl+Q")
        self.exit.setObjectName("exit")
        self.menu.addAction(self.exit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.about.menuAction())

        self.retranslateUi(MainWindow)
        self.exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

